#+STARTUP: showall
#+OPTIONS: toc:nil
#+BEGIN_EXPORT html
---
layout: post
title: A first test page converted from org. quote's test
excerpt: Some excerpt
---
#+END_EXPORT

* a sample heading for derek's blog
** a sub heading
   - jekyll blogging
     - https://www.digitalocean.com/community/tutorials/how-to-set-up-a-jekyll-development-site-on-ubuntu-16-04
     - https://www.vultr.com/docs/creating-a-jekyll-blog-on-ubuntu-16-04
     - https://orgmode.org/worg/org-tutorials/org-jekyll.html
     - https://github.com/tjaartvdwalt/jekyll-org-mode-converter some interesting notes on how to structure
       the org and jekyll sources in a single structure that can be easily pushed to github
     - installing
       #+BEGIN_EXAMPLE
       sudo apt-get install ruby ruby-dev make gc
       sudo gem install jekyll bundler
       #+END_EXAMPLE  

       #+BEGIN_EXAMPLE
       mkdir dfeich.github.io
       cd dfeich.github.io/
       #+END_EXAMPLE

       I then created the jekyll source structure
       : jekyll new jkl-src

       this required typing in my password, because jekyll seemingly pulled in some more ruby gems, and since I
       am using a centrally installed ruby, the paths to the install area requires root access. Not ideal.

       now, a first test view of the site can be gained by attaching a browser to http://localhost:4000/ after
       running
       : cd jkl-src
       : jekyll serve
     The best description for using github pages with jekyll:  
     - https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
     - https://github.com/github/pages-gem
     - I copied a number of files from https://github.com/lorepirri/cayman-blog which is built on
       top of the Cayman theme for jekyll. Github only supports a number of standard theme
       gems, so I just copied the layouts/ and includes/ directories
  
